services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  srv_sale:
    image: kodi0309/srv_sale:latest
    build:
      context: .
      dockerfile: src/Srv_Sale/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=Sales
      - IdentityServiceUrl=http://srv_id
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq
  salefinder:
    image: kodi0309/salefinder:latest
    build:
      context: .
      dockerfile: src/SaleFinder/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://mongodb
      - SaleServiceUrl=http://salefinder
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq